SELECT
    central.CODCOLIGADA,
    central.IDMOV  AS idmov_central,
    central.CODTMV AS codtmv_central,
    central.NUMEROMOV  AS numeromov_central,
    HATENDIMENTOEXT.CODSTATUS AS status_central,
    central.DATAEMISSAO AS dataemissao_central,
    central.USUARIOCRIACAO as User_Criacao,
    central.CODCCUSTO as cc_inicial,
    FCFO.NOMEFANTASIA as Fornecedor,
    TITMMOV_CENTRAL.VALORBRUTOITEM as valor_bruto_inicial,

    CASE
        WHEN HATENDIMENTOEXT.CODSTATUS = 'F' THEN 'APROVADO'
        WHEN HATENDIMENTOEXT.CODSTATUS = 'C' THEN 'REPROVADO'
        WHEN HATENDIMENTOEXT.CODSTATUS = 'A' THEN 'EM APROVAÇÃO'
        ELSE ''
    END AS APROVACAO,

    CASE
        WHEN HATENDIMENTOEXT1.CODSTATUS = 'F' THEN 'APROVADO'
        WHEN HATENDIMENTOEXT1.CODSTATUS = 'C' THEN 'REPROVADO'
        WHEN HATENDIMENTOEXT1.CODSTATUS = 'A' THEN 'EM APROVAÇÃO'
        ELSE ''
    END AS APROVACAO1,

    dest1.IDMOV AS idmov_destino1,
    dest1.CODTMV AS codtmv_destino1,
    dest1.NUMEROMOV AS numeromov_destino1,
    HATENDIMENTOEXT1.CODSTATUS AS status_destin1,
    dest1.DATAEMISSAO AS dataemissao_destino1,
    TITMMOV_DEST1.QUANTIDADE as destino_Quantidade,
    TITMMOV_DEST1.CODCCUSTO AS destino1_CC,
    TITMMOV_DEST1.CODDEPARTAMENTO as CODDEPARTAMENTO_destino1,
    TITMMOV_DEST1.CODFILIAL as Filial_destino1,
    TPRODUTO.NOMEFANTASIA AS PRODUTO_destino1,
    rel1.IDMOVDESTINO as Destino,

    dest2.IDMOV AS idmov_destino2,
    dest2.CODTMV AS codtmv_destino2,
    dest2.NUMEROMOV AS numeromov_destino2,
    HATENDIMENTOEXT2.CODSTATUS AS status_destino2,
    dest2.DATAEMISSAO AS dataemissao_destino2,
    dest2.CODCCUSTO as CC_final,
    TITMMOV_DEST2.VALORBRUTOITEM as valor_bruto_final,
    TITMMOV_DEST2.QUANTIDADE AS Quantidade,
    TITMMOV_DEST2.PRECOUNITARIO as Preco,
    dest2.SEGUNDONUMERO as AP,
    rel2.IDMOVDESTINO as Destino1

FROM TMOV AS central

LEFT JOIN TMOVRELAC rel1 (NOLOCK)
    ON rel1.CODCOLORIGEM = central.CODCOLIGADA
   AND rel1.IDMOVORIGEM  = central.IDMOV

LEFT JOIN FCFO (NOLOCK)
    ON central.CODCOLCFO = FCFO.CODCOLIGADA
   AND central.CODCFO    = FCFO.CODCFO

LEFT JOIN TITMMOV TITMMOV_CENTRAL (NOLOCK)
    ON TITMMOV_CENTRAL.CODCOLIGADA = central.CODCOLIGADA
   AND TITMMOV_CENTRAL.IDMOV       = central.IDMOV

LEFT JOIN TMOV dest1 (NOLOCK)
    ON dest1.CODCOLIGADA = rel1.CODCOLDESTINO
   AND dest1.IDMOV       = rel1.IDMOVDESTINO
   AND dest1.CODTMV      = '1.1.04'

LEFT JOIN TITMMOV TITMMOV_DEST1 (NOLOCK)
    ON TITMMOV_DEST1.CODCOLIGADA = dest1.CODCOLIGADA
   AND TITMMOV_DEST1.IDMOV       = dest1.IDMOV

LEFT JOIN TPRODUTO (NOLOCK)
    ON TPRODUTO.CODCOLPRD = TITMMOV_DEST1.CODCOLIGADA
   AND TPRODUTO.IDPRD     = TITMMOV_DEST1.IDPRD

LEFT JOIN TMOVRELAC rel2 (NOLOCK)
    ON rel2.CODCOLORIGEM = dest1.CODCOLIGADA
   AND rel2.IDMOVORIGEM  = dest1.IDMOV

LEFT JOIN TMOV dest2 (NOLOCK)
    ON dest2.CODCOLIGADA = rel2.CODCOLDESTINO
   AND dest2.IDMOV       = rel2.IDMOVDESTINO

LEFT JOIN TITMMOV TITMMOV_DEST2 (NOLOCK)
    ON TITMMOV_DEST2.CODCOLIGADA = dest2.CODCOLIGADA
   AND TITMMOV_DEST2.IDMOV       = dest2.IDMOV

LEFT JOIN TMOVATEND TMOVATEND
    ON central.IDMOV       = TMOVATEND.IDMOV
   AND central.CODCOLIGADA = TMOVATEND.CODCOLIGADA

LEFT JOIN HATENDIMENTOEXT HATENDIMENTOEXT
    ON HATENDIMENTOEXT.CODCOLIGADA    = TMOVATEND.CODCOLIGADAATEND
   AND HATENDIMENTOEXT.CODATENDIMENTO = TMOVATEND.CODATENDIMENTO
   AND HATENDIMENTOEXT.CODLOCAL       = TMOVATEND.CODLOCAL

LEFT JOIN HATENDENTE
    ON HATENDENTE.CODCOLIGADA  = HATENDIMENTOEXT.CODCOLIGADARESP
   AND HATENDENTE.CODATENDENTE = HATENDIMENTOEXT.CODATENDENTERESP

LEFT JOIN PPESSOA
    ON PPESSOA.CODIGO = HATENDENTE.CODPESSOA

LEFT JOIN HTAREFA
    ON HATENDIMENTOEXT.CODCOLIGADA        = HTAREFA.CODCOLIGADA
   AND HATENDIMENTOEXT.CODTIPOATENDIMENTO = HTAREFA.CODTIPOATENDIMENTO
   AND HATENDIMENTOEXT.CODTAREFAANTERIOR  = HTAREFA.CODTAREFA

LEFT JOIN HATENDIMENTOBASE
    ON HATENDIMENTOBASE.CODATENDIMENTO = TMOVATEND.CODATENDIMENTO
   AND HATENDIMENTOBASE.CODCOLIGADA     = TMOVATEND.CODCOLIGADA

LEFT JOIN HATENDENTE HATENDENTE2
    ON HATENDENTE2.CODCOLIGADA  = HATENDIMENTOBASE.CODCOLIGADA
   AND HATENDENTE2.CODATENDENTE = HATENDIMENTOBASE.CODATENDENTE

LEFT JOIN PPESSOA PPESSOA2
    ON PPESSOA2.CODIGO = HATENDENTE2.CODPESSOA

LEFT JOIN TMOVATEND TMOVATEND1
    ON dest1.IDMOV       = TMOVATEND1.IDMOV
   AND dest1.CODCOLIGADA = TMOVATEND1.CODCOLIGADA

LEFT JOIN HATENDIMENTOEXT HATENDIMENTOEXT1
    ON HATENDIMENTOEXT1.CODCOLIGADA    = TMOVATEND1.CODCOLIGADAATEND
   AND HATENDIMENTOEXT1.CODATENDIMENTO = TMOVATEND1.CODATENDIMENTO
   AND HATENDIMENTOEXT1.CODLOCAL       = TMOVATEND1.CODLOCAL

LEFT JOIN HATENDENTE HATENDENTE3
    ON HATENDENTE3.CODCOLIGADA  = HATENDIMENTOEXT1.CODCOLIGADARESP
   AND HATENDENTE3.CODATENDENTE = HATENDIMENTOEXT1.CODATENDENTERESP

LEFT JOIN PPESSOA PPESSOA3
    ON PPESSOA3.CODIGO = HATENDENTE3.CODPESSOA

LEFT JOIN TMOVATEND TMOVATEND2
    ON dest2.IDMOV       = TMOVATEND2.IDMOV
   AND dest2.CODCOLIGADA = TMOVATEND2.CODCOLIGADA

LEFT JOIN HATENDIMENTOEXT HATENDIMENTOEXT2
    ON HATENDIMENTOEXT2.CODCOLIGADA    = TMOVATEND2.CODCOLIGADAATEND
   AND HATENDIMENTOEXT2.CODATENDIMENTO = TMOVATEND2.CODATENDIMENTO
   AND HATENDIMENTOEXT2.CODLOCAL       = TMOVATEND2.CODLOCAL

WHERE
    central.RECCREATEDON >= DATEADD(DAY, -90, GETDATE())
    AND central.STATUS <> 'N';