SELECT
    central.CODCOLIGADA,
    central.IDMOV  AS idmov_central,
    central.CODTMV AS codtmv_central,
    central.NUMEROMOV  AS numeromov_central,
    central.STATUS   AS status_central,
    central.DATAEMISSAO AS dataemissao_central,
    central.USUARIOCRIACAO as User_Criacao,
    central.CODCCUSTO as cc_inicial,
    FCFO.NOMEFANTASIA as Fornecedor,
    central.VALORBRUTO as valor_bruto_inicial,

    dest1.IDMOV AS idmov_destino1,
    dest1.CODTMV AS codtmv_destino1,
    dest1.NUMEROMOV AS numeromov_destino1,
    dest1.STATUS AS status_destino1,
    dest1.DATAEMISSAO AS dataemissao_destino1,
    TITMMOV.QUANTIDADE as destino_Quantidade,
    TITMMOV.CODCCUSTO AS destino1_CC,
    TITMMOV.CODDEPARTAMENTO as CODDEPARTAMENTO_destino1,
    titmmov.codfilial as Filia_destino1,
    TPRODUTO.NOMEFANTASIA AS PRODUTO_destino1,


    dest2.IDMOV AS idmov_destino2,
    dest2.CODTMV AS codtmv_destino2,
    dest2.NUMEROMOV AS numeromov_destino2,
    dest2.STATUS AS status_destino2,
    dest2.DATAEMISSAO AS dataemissao_destino2,
    dest2.CODCCUSTO as CC_final,
    dest2.VALORBRUTO as valor_bruto_final

FROM TMOV as central

LEFT JOIN TMOVRELAC rel1 (NOLOCK)
    ON rel1.CODCOLORIGEM = central.CODCOLIGADA
   AND rel1.IDMOVORIGEM  = central.IDMOV

   INNER JOIN FCFO (NOLOCK)
   ON central.CODCOLCFO = FCFO.CODCOLIGADA
   AND central.CODCFO = FCFO.CODCFO

LEFT JOIN TMOV dest1 (NOLOCK)
    ON dest1.CODCOLIGADA = rel1.CODCOLDESTINO
   AND dest1.IDMOV = rel1.IDMOVDESTINO
   AND dest1.CODTMV  = '1.1.04'

   INNER JOIN TITMMOV (NOLOCK)
   ON TITMMOV.CODCOLIGADA = dest1.CODCOLIGADA
   AND TITMMOV.IDMOV = dest1.IDMOV

   INNER JOIN TPRODUTO (NOLOCK)
   ON TPRODUTO.CODCOLPRD = TITMMOV.CODCOLIGADA
   AND TPRODUTO.IDPRD = TITMMOV.IDPRD

LEFT JOIN TMOVRELAC rel2 (NOLOCK)
    ON rel2.CODCOLORIGEM = dest1.CODCOLIGADA
   AND rel2.IDMOVORIGEM  = dest1.IDMOV

LEFT JOIN TMOV dest2 (NOLOCK)
    ON dest2.CODCOLIGADA = rel2.CODCOLDESTINO
   AND dest2.IDMOV = rel2.IDMOVDESTINO

   inner JOIN TMOVATEND ON central.IDMOV = TMOVATEND.IDMOV AND central.CODCOLIGADA = TMOVATEND.CODCOLIGADA
     inner JOIN HATENDIMENTOEXT ON HATENDIMENTOEXT.CODCOLIGADA = TMOVATEND.CODCOLIGADAATEND AND HATENDIMENTOEXT.CODATENDIMENTO = TMOVATEND.CODATENDIMENTO AND HATENDIMENTOEXT.CODLOCAL = TMOVATEND.CODLOCAL
inner JOIN HATENDENTE ON HATENDENTE.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADARESP AND HATENDENTE.CODATENDENTE = HATENDIMENTOEXT.CODATENDENTERESP
inner JOIN PPESSOA ON PPESSOA.CODIGO = HATENDENTE.CODPESSOA
left JOIN HTAREFA ON HATENDIMENTOEXT.CODCOLIGADA = HTAREFA.CODCOLIGADA AND HATENDIMENTOEXT.CODTIPOATENDIMENTO = HTAREFA.CODTIPOATENDIMENTO AND HATENDIMENTOEXT.CODTAREFAANTERIOR = HTAREFA.CODTAREFA
LEFT JOIN  HATENDIMENTOBASE ON HATENDIMENTOBASE.CODATENDIMENTO = TMOVATEND.CODATENDIMENTO AND HATENDIMENTOBASE.CODCOLIGADA = TMOVATEND.CODCOLIGADA
inner JOIN HATENDENTE HATENDENTE2 ON HATENDENTE2.CODCOLIGADA = HATENDIMENTOBASE.CODCOLIGADA AND HATENDENTE2.CODATENDENTE = HATENDIMENTOBASE.CODATENDENTE
inner JOIN PPESSOA PPESSOA2 ON PPESSOA2.CODIGO = HATENDENTE2.CODPESSOA


inner JOIN TMOVATEND TMOVATEND1 ON dest1.IDMOV = TMOVATEND1.IDMOV AND dest1.CODCOLIGADA = TMOVATEND.CODCOLIGADA
     inner JOIN HATENDIMENTOEXT HATENDIMENTOEXT1 ON HATENDIMENTOEXT1.CODCOLIGADA = TMOVATEND1.CODCOLIGADAATEND AND HATENDIMENTOEXT1.CODATENDIMENTO = TMOVATEND1.CODATENDIMENTO AND HATENDIMENTOEXT1.CODLOCAL = TMOVATEND1.CODLOCAL
inner JOIN HATENDENTE HATENDENTE1 ON HATENDENTE1.CODCOLIGADA = HATENDIMENTOEXT1.CODCOLIGADARESP AND HATENDENTE1.CODATENDENTE = HATENDIMENTOEXT1.CODATENDENTERESP
inner JOIN PPESSOA PPESSOA1 ON PPESSOA1.CODIGO = HATENDENTE1.CODPESSOA
left JOIN HTAREFA HTAREFA1 ON HATENDIMENTOEXT1.CODCOLIGADA = HTAREFA1.CODCOLIGADA AND HATENDIMENTOEXT1.CODTIPOATENDIMENTO = HTAREFA1.CODTIPOATENDIMENTO AND HATENDIMENTOEXT1.CODTAREFAANTERIOR = HTAREFA1.CODTAREFA
LEFT JOIN  HATENDIMENTOBASE HATENDIMENTOBASE1 ON HATENDIMENTOBASE1.CODATENDIMENTO = TMOVATEND1.CODATENDIMENTO AND HATENDIMENTOBASE1.CODCOLIGADA = TMOVATEND1.CODCOLIGADA
inner JOIN HATENDENTE HATENDENTE1 ON HATENDENTE1.CODCOLIGADA = HATENDIMENTOBASE1.CODCOLIGADA AND HATENDENTE1.CODATENDENTE = HATENDIMENTOBASE1.CODATENDENTE
inner JOIN PPESSOA PPESSOA1 ON PPESSOA1.CODIGO = HATENDENTE2.CODPESSOA

WHERE
    central.RECCREATEDON >= DATEADD(DAY, -150, GETDATE())
    AND central.STATUS <> 'N'

    
